layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 100  
  exclude:
    archived: true
    forks: true
    projects:
    - VSCODE_EXE
    - vscode-fonts
    - React-app-Material-UI
    - Material-ui-themes
    - TQ_client
    - fonts_evaluation
    - gitfolio
    - admin-pages
    - ud_JS_understanding_the_weird_parts
    - TQ_admin
    - 1610-BJJ
    - this-is-where-i-write
    - site-terms-policies
    - privacy-and-terms.cliff-crerar.tech
    - angular.io-tutorial
    - pdf-docs-portal
    - next.js-easy
    - next.js-blog
    - admin-pages
    - temp-demo-sites
    - nodes-google-cloud-datastore-tutorial
    # - repo-name

social_media:
  behance: cliff-crerar
  dribbble: cliffenator
  facebook: cliff.crerar
  # hackerrank: your_username
  instagram: cliffenator
  # keybase: your_username
  linkedin: cliff-crerar
  mastodon: cliffcrerar
  medium: cliff.crerar
  stackoverflow: cliff-crerar
  telegram: cliffcrerar
  twitter: Cliffenator
  # unsplash: your_username
  # vk: your_username
  myportal: https://cliff-crerar.tech
  youtube: MrBeamerguy

topics:
- name: Amazon Web Services
  web_url: https://youtu.be/RPis5mbM8c8
  image_url: https://i.imgur.com/eeYUFCO.jpg

- name: Google Cloud Platform
  web_url: https://youtu.be/cKUeV6FJP_U
  image_url: https://shinesg.files.wordpress.com/2018/09/google-cloud-platform.png

- name: MS Azure Cloud Platform
  web_url: https://youtu.be/KXkBZCe699A
  image_url: https://www.yobyot.com/wp-content/uploads/2018/05/azurelogo-300x242.jpg

- name: NextJS & React
  web_url: https://nextjs.org/docs
  image_url: https://www.honext.io/static/images/next_logo.png
  
- name: Angular
  web_url: https://angular.io/
  image_url: https://cdn-cloudflare.ga/assets/site-logo/angular/ng-logo.png
  
- name: User experience design
  web_url: https://www.interaction-design.org/literature/topics/ux-design
  image_url: https://images.techhive.com/images/article/2016/08/ecommerce_ux_2-100678246-large.jpg
  
- name: Material Design
  web_url: https://youtu.be/m1diVY4Uzjc
  image_url: https://misc-webassets.c1i44.now.sh/mat-design.png

- name: Web technology applications
  web_url: https://www.interaction-design.org/literature/topics/web-design
  image_url: https://1z2y5h3h3ees3m9gz33a9jbx-wpengine.netdna-ssl.com/wp-content/uploads/2018/02/web-design-agency-cape-town.jpg

- name: Coding
  web_url: https://youtu.be/cKhVupvyhKk
  image_url: https://freeiconshop.com/wp-content/uploads/edd/code-flat.png