layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: none  
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

  social_media:
  # behance: https://www.behance.net/cliff-crerar
  # dribbble: https://dribbble.com/cliffenator/buckets
  # facebook: https://www.facebook.com/cliff.crerar
  # hackerrank: your_username
  # instagram: https://www.instagram.com/cliffenator/
  # keybase: your_username
  # linkedin: https://www.linkedin.com/in/cliff-crerar/
  # mastodon: @cliffcrerar
  # medium: https://medium.com/@cliff.crerar/highlights
  # stackoverflow: https://stackoverflow.com/users/5599914/cliff-crerar
  # telegram: cliffcrerar
  # twitter: https://twitter.com/Cliffenator
  # unsplash: your_username
  # vk: your_username
  website: https://cliff-crerar.tech/
  youtube: MrBeamerguy

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
